### PR TITLE
Use Value instead of Token for random stock

### PR DESCRIPTION
**Pull request by TheGiraffe3**

### CODE REVIEW

**Comment by TheGiraffe3** [comment]
I'm not sure what these errors mean...

**Comment by TomGoodIdea** [comment]
Value returns a double, while Token returns a string

**Comment by TheGiraffe3** [comment]
Finally got checks to work, thanks!
TomGoodIdea, do you think this will resolve the comment about removing `stoi`?

**Comment by TomGoodIdea** [comment]
> do you think this will resolve the comment about removing `stoi`?

Yes.
Also you can remove the `double()` conversion, because `Value()` is already a double.

**Pull request merged**
